### ISSUE TITLE
Add an open source license to project?

### ISSUE THREAD

**Issue by downeymj** [abtassociates/mecvision#1]
Hi there! Thank you so much for publishing the source code to this project, and for providing documentation about how to install it.

Unfortunately, since there is not yet an open source license provided with the code, the code is "all rights reserved" and folks don't have the legal ability to use, study, share, and improve this work.

Please consider looking at the wide variety of available open source licenses and adding one to this project to maximize its value. More information about the options is available at: https://choosealicense.com/

Thanks for your consideration!

**Comment by gabrielkrieshok** [comment]
Added GPL license.
